spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/AccountDB
    username: postgres
    password: turan8726

  application:
    name: ms-current-account-service

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true

  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml
    enabled: true

  profiles:
    active: dev

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE

server:
  port: 8082

account:
  max-accounts-per-customer: 3










